---
- name: Deploy Node.js App with Apache using Ansible
  hosts: all
  become: yes
  tasks:
    - name: Add NodeSource repository key for Node.js 14.x
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository for Node.js 14.x
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install Node.js dependencies
      npm:
        path: /var/www/html/NodeJs_Application_AzureKubernetesCluster
        state: present
        executable: npm
      become: yes

    - name: Change ownership of application directory
      file:
        path: /var/www/html/NodeJs_Application_AzureKubernetesCluster
        owner: samirwadkar31
        group: samirwadkar31
        recurse: yes

    - name: Copy Apache configuration file
      copy:
        src: /var/www/html/NodeJs_Application_AzureKubernetesCluster/apache_nodejs.conf
        dest: /etc/apache2/sites-available/nodejs.conf

    - name: Enable Node.js site
      command: a2ensite nodejs.conf

    - name: Disable default site
      command: a2dissite 000-default.conf

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
